---
name: Update versions.json

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1' # Every Monday at 05:00

jobs:
  update-versions:
    name: Update versions.json from PyPI
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v6.0.2
      - name: 🏗 Set up UV
        uses: astral-sh/setup-uv@v8.0.0
        with:
          version: "latest"
          enable-cache: true
      - name: 🏗 Install workflow dependencies
        run: uv sync
      - name: ♻️ Run update_versions.py
        run: uv run python scripts/update_versions.py
      - name: 👍 Commit & create PR if changed
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          commit-message: "♻️ Update versions.json"
          title: "♻️ Update versions.json"
          body: "This PR updates dependencies in versions.json to the latest versions from PyPI."
          branch: chore/update-versions
          delete-branch: true
          labels: dependencies
